#include "mc_routine.h"
#include "mc_dispatch.h"
//---------------------------------------------------------------------------
void mc_dispatchmsg(TMcPacket *packet){
//to map user message to handler 
  BEGIN_MESSAGE_MAP_ONLINE
     MESSAGE_HANDLER(MSG_DSR_COMMJSON)  
     MESSAGE_HANDLER(MSG_VSA_LIVE)  
     MESSAGE_HANDLER(MSG_USA_LIVE)
     MESSAGE_HANDLER(MSG_USA_LIVE_RET)
     MESSAGE_HANDLER(MSG_DSA_WAKEUP)
     MESSAGE_HANDLER(MSG_USA_NOTIFY_STATE)
     MESSAGE_HANDLER(MSG_USA_NOTIFY_MSGBOX);
     MESSAGE_HANDLER(MSG_DSR_MCU_CHECKVERSION)
     MESSAGE_HANDLER(MSG_DSR_MCU_UPGRADE)
     MESSAGE_HANDLER(MSG_TSR_HEARTBEAT)
     MESSAGE_HANDLER(MSG_DSR_APPLYFORUID)
     MESSAGE_HANDLER(MSG_DSR_SYNC)
     MESSAGE_HANDLER(MSG_USR_GETUSERHEAD)
     MESSAGE_HANDLER(MSG_USR_CHANGEHEAD)
     MESSAGE_HANDLER(MSG_USR_GETUSERINFO)
     MESSAGE_HANDLER(MSG_USR_CHANGENICK)
     MESSAGE_HANDLER(MSG_USR_CHANGESEX)
     MESSAGE_HANDLER(MSG_USR_ACCEPTMSGPUSH)
     MESSAGE_HANDLER(MSG_USR_ACCEPTLIVEPUSH)
     MESSAGE_HANDLER(MSG_USR_LOGOUT)
     MESSAGE_HANDLER(MSG_USR_BIND)
     MESSAGE_HANDLER(MSG_USR_GETBINDLIST)
     MESSAGE_HANDLER(MSG_VSR_GETBINDUSER)
     MESSAGE_HANDLER(MSG_DSR_NOTIFY_STATE)
     MESSAGE_HANDLER(MSG_DSR_NOTIFY_STRIKE)
     MESSAGE_HANDLER(MSG_DSR_NOTIFY_LOWPOWER)
     MESSAGE_HANDLER(MSG_USR_WAKEUP)
     MESSAGE_HANDLER(MSG_USR_LIVE)
     MESSAGE_HANDLER(MSG_VSR_LIVE)
     MESSAGE_HANDLER(MSG_VSR_LIVE_RET)
     MESSAGE_HANDLER(MSG_USR_LIVE_STOP)
     MESSAGE_HANDLER(MSG_DSR_UPLOAD_GPS)
     MESSAGE_HANDLER(MSG_DSR_UPLOAD_BEHAVIOR)
     MESSAGE_HANDLER(MSG_DSR_UPLOAD_IMSI)
     MESSAGE_HANDLER(MSG_USR_QUERY_FLOWPACKAGE)
     MESSAGE_HANDLER(MSG_USR_READ_OFFLINEMSG)
     MESSAGE_HANDLER(MSG_USR_DELETE_OFFLINEMSG);
     MESSAGE_HANDLER(MSG_DSR_QUERY_SN808);
     MESSAGE_HANDLER(MSG_DSR_QUERY_SNQQ);
     MESSAGE_HANDLER(MSG_USR_QUERY_SN_FROM808);
     MESSAGE_HANDLER(MSG_USR_QUERY_GPS);   	    	 
     MESSAGE_HANDLER(MSG_DSR_UPDATE_BOXSN);
     MESSAGE_HANDLER(MSG_DSR_NOTIFY_SNAPSHOT);
     MESSAGE_HANDLER(MSG_USR_QUERY_STATE);                  
     MESSAGE_HANDLER(MSG_DSA_QUERY_STATE);
  BEGIN_MESSAGE_MAP_ANYWAY
     MESSAGE_HANDLER(MSG_USR_QUERY_SN808);
     MESSAGE_HANDLER(MSG_USR_QUERY_ACCESSNO);
     MESSAGE_HANDLER(MSG_USA_KICKOFF)
     MESSAGE_HANDLER(MSG_DSR_LOGIN) 
     MESSAGE_HANDLER(MSG_USR_LOGIN)
     MESSAGE_HANDLER(MSG_USR_LOGIN2) 
     MESSAGE_HANDLER(MSG_TSR_SPYLOGIN)
     MESSAGE_HANDLER(MSG_USR_QUERY_VERSION)
     MESSAGE_HANDLER(MSG_USR_REGIST)
     MESSAGE_HANDLER(MSG_USR_CHANGEPSW)  //修改用户密码（登录状态通过原密码修改，离线时通过验证码修改）
     MESSAGE_HANDLER(MSG_USR_POST_ADVICE)
     MESSAGE_HANDLER(MSG_USR_VERIFYCODE)
     MESSAGE_HANDLER(MSG_USR_CONFIGS)
     MESSAGE_HANDLER(MSG_BSR_NOTIFY)
  END_MESSAGE_MAP
}
//---------------------------------------------------------------------------
/*todolist
##################todo_first_level:
◆hsk_init -增加包检验回调函数;hsk_readPacket取代hsk_readData;
◆短信限制（Vericode合并）
◆推广消息web端发送页面
√多线程流量监测预警
√FindTask Lock与解锁机制（保护TaskData)
##################todo_second_level:  
◆ 除了登录及心跳包，其他协议使用TCP/UDP均可。
◆ 登录必须用UDP包，以便记录客服端UDP地址，心跳包也必须用UDP包，以便维持客户端NAT映射表。保证服务器随时可以通过UDP地址找到客户端。
◆现在MySQL连接超时没用心跳查询，而是设置MySQL加长超时时间为1年。
◆目前网络数据接收采用独立线程，而数据发送不采用独立线程，而是通过适当增加socket的发送缓冲大小，来避免发送大数据时的线程阻塞。
##################rules:  
◆ 1. 终端/设备的状态是指摄像头的状态，MiFI盒子的状态不记录
  2. 摄像头通过盒子账号上报状态时，要更新到摄像头在内存以及数据库中的状态
  3. 收到APP唤醒请求指令时，绑定了盒子则去唤醒盒子，否则直接唤醒绑定设备
  5. 盒子心跳超时，更新数据库状态
  6. 增加盒子专用登录指令
  7. 盒子登录与摄像头登录互斥
  8. 新增接口：摄像头上报盒子绑带关系
◆  。
*/ 
